blank_issues_enabled: false
contact_links:
    - name: ğŸ¤” Questions and Help
      url: https://github.com/rnmapbox/maps/discussions/categories/q-a
      about: Looking for help with your app? Please use discussions or gitter or stack overflow
    - name: ğŸš€ Discussions and Proposals
      url: https://github.com/rnmapbox/maps/discussions/categories/ideas
      about: Discuss the future of RNMapbox, submit feature requests
    - name: âš ï¸ Sponsor-only Deprecated v10 / Old Architecture Support
      url: https://github.com/sponsors/rnmapbox
      about: Support for v10.x and old architecture is only available to sponsors. Visit this page to become a sponsor and access special support options.
    - name: ğŸ“š Sponsors Wiki
      url: https://github.com/rnmapbox/sponsors/wiki
      about: Details on sponsorship tiers, benefits, and support options
