name: CI Builds requiring mapbox tokens

on:
  workflow_call:
    inputs:
      NVMRC:
        required: true
        type: string
      env_name:
        required: false
        type: string
        default: default
      ref:
        required: false
        type: string
    secrets:
      MAPBOX_ACCESS_TOKEN:
        required: false
      ENV_MAPBOX_ACCESS_TOKEN:
        required: false

concurrency:
  group: ${{ github.head_ref || github.run_id }}-ci-with-tokens
  cancel-in-progress: true

jobs:
  # Note: As of 10.3.0, only Mapbox v11 + New Architecture (Fabric) is supported
  # v10 and old architecture configurations have been removed

  call_android_workflow_11_fabric:
    name: "Android/Mapbox11/Fabric"
    uses: ./.github/workflows/android-actions.yml
    with:
      env_name: ${{ inputs.env_name }}
      ref: ${{ inputs.ref }}
      NVMRC: ${{ inputs.NVMRC }}
      MAP_IMPL: mapbox11
      NEW_ARCH: true
    secrets:
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      ENV_MAPBOX_ACCESS_TOKEN: ${{ secrets.ENV_MAPBOX_ACCESS_TOKEN }}

  call_ios_workflow_11_fabric:
    name: "iOS/Mapbox11/Fabric"
    uses: ./.github/workflows/ios-actions.yml
    with:
      env_name: ${{ inputs.env_name }}
      ref: ${{ inputs.ref }}
      NVMRC: ${{ inputs.NVMRC }}
      MAP_IMPL: mapbox11
      NEW_ARCH: true
    secrets:
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      ENV_MAPBOX_ACCESS_TOKEN: ${{ secrets.ENV_MAPBOX_ACCESS_TOKEN }}

  call_web_workflow:
    name: "Web/Mapbox"
    uses: ./.github/workflows/web-actions.yml
    with:
      env_name: ${{ inputs.env_name }}
      ref: ${{ inputs.ref }}
      NVMRC: ${{ inputs.NVMRC }}
    secrets:
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      ENV_MAPBOX_ACCESS_TOKEN: ${{ secrets.ENV_MAPBOX_ACCESS_TOKEN }}
